from __future__ import annotations

import argparse
import json
import sqlite3
from pathlib import Path

from init_db import DEFAULT_DB_PATH, init_database


TABLE_ORDER = [
    "tenants",
    "workspaces",
    "products",
    "sellers",
    "keywords",
    "market_score",
    "opportunity_score",
    "analysis_queue",
    "action_queue",
    "action_history",
    "upload_queue",
    "approval_history",
    "users",
    "roles",
    "permissions",
    "user_roles",
    "tenant_users",
    "operation_logs",
    "shopee_orders",
    "shopee_products",
    "shopee_inventory",
    "decision_feedback",
    "decision_history",
    "decision_business_outcomes",
    "decision_learning_adjustments",
    "business_impact_results",
    "profit_snapshot",
    "product_profit",
    "inventory_snapshot",
    "inventory_stock",
    "inventory_risk",
    "reorder_recommendation",
    "crawl_logs",
    "data_quality_report",
]


def rows_to_insert() -> dict[str, list[dict[str, object]]]:
    tenants = [
        {
            "tenant_id": "demo_tenant",
            "name": "Brazil Demo Tenant",
            "plan_type": "pro",
            "created_at": "2026-06-19T09:00:00-03:00",
        },
        {
            "tenant_id": "growth_tenant",
            "name": "Growth Sandbox Tenant",
            "plan_type": "free",
            "created_at": "2026-06-19T09:20:00-03:00",
        },
    ]

    workspaces = [
        {
            "workspace_id": "demo_workspace_br",
            "tenant_id": "demo_tenant",
            "name": "Brazil Commerce Workspace",
            "shop_count": 6,
            "created_at": "2026-06-19T09:05:00-03:00",
        },
        {
            "workspace_id": "growth_workspace_br",
            "tenant_id": "growth_tenant",
            "name": "Growth Testing Workspace",
            "shop_count": 1,
            "created_at": "2026-06-19T09:25:00-03:00",
        },
    ]

    sellers = [
        {
            "seller_uid": "seller_9a54d2b8",
            "platform": "Shopee",
            "market_code": "br",
            "platform_shop_id": "SHOP-001",
            "shop_url": "https://example.local/shopee/shop-001",
            "shop_name": "Casa Modular BR",
            "followers": 18200,
            "rating": 4.8,
            "product_count": 154,
            "location": "Sao Paulo",
            "response_rate": 0.96,
            "data_confidence": 0.93,
            "first_seen_at": "2026-05-20T09:00:00-03:00",
            "last_seen_at": "2026-06-16T09:15:00-03:00",
            "platform_updated_at": "2026-06-16T08:55:00-03:00",
            "raw_seller_id_latest": "raw_seller_20260616_a1",
            "is_active": 1,
        },
        {
            "seller_uid": "seller_f71a33c2",
            "platform": "Mercado Livre",
            "market_code": "br",
            "platform_shop_id": "SELLER-002",
            "shop_url": "https://example.local/ml/seller-002",
            "shop_name": "Termica Prime",
            "followers": 9200,
            "rating": 4.6,
            "product_count": 88,
            "location": "Curitiba",
            "response_rate": 0.91,
            "data_confidence": 0.9,
            "first_seen_at": "2026-05-28T10:00:00-03:00",
            "last_seen_at": "2026-06-16T09:40:00-03:00",
            "platform_updated_at": "2026-06-16T08:44:00-03:00",
            "raw_seller_id_latest": "raw_seller_20260616_b2",
            "is_active": 1,
        },
        {
            "seller_uid": "seller_43ae9d10",
            "platform": "Amazon BR",
            "market_code": "br",
            "platform_shop_id": "STORE-003",
            "shop_url": "https://example.local/amazon/store-003",
            "shop_name": "Luz Compacta",
            "followers": 4100,
            "rating": 4.4,
            "product_count": 63,
            "location": "Belo Horizonte",
            "response_rate": 0.88,
            "data_confidence": 0.86,
            "first_seen_at": "2026-05-30T11:00:00-03:00",
            "last_seen_at": "2026-06-16T09:50:00-03:00",
            "platform_updated_at": "2026-06-16T08:48:00-03:00",
            "raw_seller_id_latest": "raw_seller_20260616_c3",
            "is_active": 1,
        },
        {
            "seller_uid": "seller_801de445",
            "platform": "TikTok Shop BR",
            "market_code": "br",
            "platform_shop_id": "CREATOR-004",
            "shop_url": "https://example.local/tiktok/creator-004",
            "shop_name": "Glow Travel Lab",
            "followers": 24800,
            "rating": 4.7,
            "product_count": 47,
            "location": "Rio de Janeiro",
            "response_rate": 0.94,
            "data_confidence": 0.92,
            "first_seen_at": "2026-05-26T15:00:00-03:00",
            "last_seen_at": "2026-06-16T10:00:00-03:00",
            "platform_updated_at": "2026-06-16T09:02:00-03:00",
            "raw_seller_id_latest": "raw_seller_20260616_d4",
            "is_active": 1,
        },
        {
            "seller_uid": "seller_2cc8a147",
            "platform": "Temu",
            "market_code": "br",
            "platform_shop_id": "TEMU-SHOP-005",
            "shop_url": "https://example.local/temu/shop-005",
            "shop_name": "Drive Utility Lab",
            "followers": 13600,
            "rating": 4.5,
            "product_count": 112,
            "location": "Campinas",
            "response_rate": 0.9,
            "data_confidence": 0.89,
            "first_seen_at": "2026-05-24T12:00:00-03:00",
            "last_seen_at": "2026-06-16T10:06:00-03:00",
            "platform_updated_at": "2026-06-16T09:04:00-03:00",
            "raw_seller_id_latest": "raw_seller_20260616_e5",
            "is_active": 1,
        },
        {
            "seller_uid": "seller_0f3b5128",
            "platform": "AliExpress",
            "market_code": "br",
            "platform_shop_id": "AE-STORE-006",
            "shop_url": "https://example.local/aliexpress/store-006",
            "shop_name": "Compact Living Maker",
            "followers": 8700,
            "rating": 4.3,
            "product_count": 96,
            "location": "Recife",
            "response_rate": 0.87,
            "data_confidence": 0.84,
            "first_seen_at": "2026-05-22T13:20:00-03:00",
            "last_seen_at": "2026-06-16T10:10:00-03:00",
            "platform_updated_at": "2026-06-16T09:08:00-03:00",
            "raw_seller_id_latest": "raw_seller_20260616_f6",
            "is_active": 1,
        },
    ]

    products = [
        {
            "product_uid": "prod_8fd1a2c0",
            "platform": "Shopee",
            "market_code": "br",
            "platform_product_id": "ITEM-001",
            "platform_shop_id": "SHOP-001",
            "product_url": "https://example.local/shopee/item-001",
            "title_current": "Organizador de Cozinha Modular",
            "price_amount": 39.9,
            "market_currency": "BRL",
            "original_price_amount": 49.9,
            "rating": 4.8,
            "review_count": 123,
            "sold_count_text": "1k+ vendidos",
            "image_url": "https://example.local/assets/item-001.jpg",
            "seller_uid": "seller_9a54d2b8",
            "category_path": "Casa > Organizacao > Cozinha",
            "availability_status": "in_stock",
            "upload_status": "mock_only",
            "data_confidence": 0.95,
            "first_seen_at": "2026-05-20T09:10:00-03:00",
            "last_seen_at": "2026-06-16T09:12:00-03:00",
            "platform_updated_at": "2026-06-16T08:54:00-03:00",
            "raw_product_id_latest": "raw_product_20260616_a1",
            "created_at": "2026-05-20T09:10:00-03:00",
            "updated_at": "2026-06-16T09:12:00-03:00",
        },
        {
            "product_uid": "prod_7bb2f310",
            "platform": "Mercado Livre",
            "market_code": "br",
            "platform_product_id": "MLB-002",
            "platform_shop_id": "SELLER-002",
            "product_url": "https://example.local/ml/mlb-002",
            "title_current": "Garrafa Termica Inox 750ml",
            "price_amount": 58.5,
            "market_currency": "BRL",
            "original_price_amount": 68.0,
            "rating": 4.6,
            "review_count": 89,
            "sold_count_text": "500+ vendidos",
            "image_url": "https://example.local/assets/mlb-002.jpg",
            "seller_uid": "seller_f71a33c2",
            "category_path": "Casa > Cozinha > Garrafas",
            "availability_status": "in_stock",
            "upload_status": "mock_only",
            "data_confidence": 0.91,
            "first_seen_at": "2026-05-28T10:15:00-03:00",
            "last_seen_at": "2026-06-16T09:35:00-03:00",
            "platform_updated_at": "2026-06-16T08:42:00-03:00",
            "raw_product_id_latest": "raw_product_20260616_b2",
            "created_at": "2026-05-28T10:15:00-03:00",
            "updated_at": "2026-06-16T09:35:00-03:00",
        },
        {
            "product_uid": "prod_2c0d88aa",
            "platform": "Amazon BR",
            "market_code": "br",
            "platform_product_id": "AMZ-003",
            "platform_shop_id": "STORE-003",
            "product_url": "https://example.local/amazon/amz-003",
            "title_current": "Luminaria LED Recarregavel",
            "price_amount": 76.2,
            "market_currency": "BRL",
            "original_price_amount": 89.9,
            "rating": 4.4,
            "review_count": 57,
            "sold_count_text": "300+ vendidos",
            "image_url": "https://example.local/assets/amz-003.jpg",
            "seller_uid": "seller_43ae9d10",
            "category_path": "Casa > Iluminacao > Mesa",
            "availability_status": "in_stock",
            "upload_status": "mock_only",
            "data_confidence": 0.88,
            "first_seen_at": "2026-05-30T11:20:00-03:00",
            "last_seen_at": "2026-06-16T09:46:00-03:00",
            "platform_updated_at": "2026-06-16T08:46:00-03:00",
            "raw_product_id_latest": "raw_product_20260616_c3",
            "created_at": "2026-05-30T11:20:00-03:00",
            "updated_at": "2026-06-16T09:46:00-03:00",
        },
        {
            "product_uid": "prod_97c41f03",
            "platform": "TikTok Shop BR",
            "market_code": "br",
            "platform_product_id": "TT-004",
            "platform_shop_id": "CREATOR-004",
            "product_url": "https://example.local/tiktok/tt-004",
            "title_current": "Kit Skincare Viagem",
            "price_amount": 49.99,
            "market_currency": "BRL",
            "original_price_amount": 62.5,
            "rating": 4.7,
            "review_count": 211,
            "sold_count_text": "2k+ vendidos",
            "image_url": "https://example.local/assets/tt-004.jpg",
            "seller_uid": "seller_801de445",
            "category_path": "Beleza > Skincare > Kits",
            "availability_status": "limited_stock",
            "upload_status": "mock_only",
            "data_confidence": 0.94,
            "first_seen_at": "2026-05-26T15:25:00-03:00",
            "last_seen_at": "2026-06-16T09:58:00-03:00",
            "platform_updated_at": "2026-06-16T09:01:00-03:00",
            "raw_product_id_latest": "raw_product_20260616_d4",
            "created_at": "2026-05-26T15:25:00-03:00",
            "updated_at": "2026-06-16T09:58:00-03:00",
        },
        {
            "product_uid": "prod_5d4e1c7b",
            "platform": "Temu",
            "market_code": "br",
            "platform_product_id": "TEMU-005",
            "platform_shop_id": "TEMU-SHOP-005",
            "product_url": "https://example.local/temu/temu-005",
            "title_current": "Suporte Magnetico para Celular no Carro",
            "price_amount": 29.9,
            "market_currency": "BRL",
            "original_price_amount": 37.9,
            "rating": 4.5,
            "review_count": 142,
            "sold_count_text": "900+ vendidos",
            "image_url": "https://example.local/assets/temu-005.jpg",
            "seller_uid": "seller_2cc8a147",
            "category_path": "Automotivo > Acessorios > Suportes",
            "availability_status": "in_stock",
            "upload_status": "mock_only",
            "data_confidence": 0.9,
            "first_seen_at": "2026-05-24T12:15:00-03:00",
            "last_seen_at": "2026-06-16T10:04:00-03:00",
            "platform_updated_at": "2026-06-16T09:03:00-03:00",
            "raw_product_id_latest": "raw_product_20260616_e5",
            "created_at": "2026-05-24T12:15:00-03:00",
            "updated_at": "2026-06-16T10:04:00-03:00",
        },
        {
            "product_uid": "prod_f42ab991",
            "platform": "AliExpress",
            "market_code": "br",
            "platform_product_id": "AE-006",
            "platform_shop_id": "AE-STORE-006",
            "product_url": "https://example.local/aliexpress/ae-006",
            "title_current": "Mini Seladora Portatil para Embalagem",
            "price_amount": 22.8,
            "market_currency": "BRL",
            "original_price_amount": 31.5,
            "rating": 4.3,
            "review_count": 63,
            "sold_count_text": "400+ vendidos",
            "image_url": "https://example.local/assets/ae-006.jpg",
            "seller_uid": "seller_0f3b5128",
            "category_path": "Casa > Cozinha > Gadgets",
            "availability_status": "low_stock",
            "upload_status": "mock_only",
            "data_confidence": 0.85,
            "first_seen_at": "2026-05-22T13:30:00-03:00",
            "last_seen_at": "2026-06-16T10:08:00-03:00",
            "platform_updated_at": "2026-06-16T09:06:00-03:00",
            "raw_product_id_latest": "raw_product_20260616_f6",
            "created_at": "2026-05-22T13:30:00-03:00",
            "updated_at": "2026-06-16T10:08:00-03:00",
        },
    ]

    keywords = [
        {
            "keyword_uid": "kw_br_0f4a2b1c",
            "platform": "Shopee",
            "market_code": "br",
            "language_code": "pt-BR",
            "normalized_keyword": "organizador cozinha",
            "original_keyword": "organizador cozinha",
            "category_hint": "Home Storage",
            "first_seen_at": "2026-05-20T09:05:00-03:00",
            "last_seen_at": "2026-06-16T09:00:00-03:00",
            "latest_result_count": 1240,
            "competition_level": "medium",
            "seasonality_tag": "stable",
            "status": "active",
            "notes": "Strong baseline home keyword.",
        },
        {
            "keyword_uid": "kw_br_f0b98d22",
            "platform": "Mercado Livre",
            "market_code": "br",
            "language_code": "pt-BR",
            "normalized_keyword": "garrafa termica",
            "original_keyword": "garrafa termica",
            "category_hint": "Drinkware",
            "first_seen_at": "2026-05-28T10:00:00-03:00",
            "last_seen_at": "2026-06-16T09:20:00-03:00",
            "latest_result_count": 860,
            "competition_level": "medium",
            "seasonality_tag": "stable",
            "status": "active",
            "notes": "Consistent evergreen keyword.",
        },
        {
            "keyword_uid": "kw_br_661db203",
            "platform": "Amazon BR",
            "market_code": "br",
            "language_code": "pt-BR",
            "normalized_keyword": "luminaria recarregavel",
            "original_keyword": "luminaria recarregavel",
            "category_hint": "Portable Lighting",
            "first_seen_at": "2026-05-30T11:00:00-03:00",
            "last_seen_at": "2026-06-16T09:30:00-03:00",
            "latest_result_count": 540,
            "competition_level": "low",
            "seasonality_tag": "uptrend",
            "status": "active",
            "notes": "Emerging portable lighting keyword.",
        },
        {
            "keyword_uid": "kw_br_202ff870",
            "platform": "TikTok Shop BR",
            "market_code": "br",
            "language_code": "pt-BR",
            "normalized_keyword": "kit skincare viagem",
            "original_keyword": "kit skincare viagem",
            "category_hint": "Beauty Travel",
            "first_seen_at": "2026-05-26T15:00:00-03:00",
            "last_seen_at": "2026-06-16T09:45:00-03:00",
            "latest_result_count": 980,
            "competition_level": "high",
            "seasonality_tag": "uptrend",
            "status": "active",
            "notes": "High-interest beauty travel keyword.",
        },
        {
            "keyword_uid": "kw_br_9dc5810e",
            "platform": "Temu",
            "market_code": "br",
            "language_code": "pt-BR",
            "normalized_keyword": "suporte magnetico carro",
            "original_keyword": "suporte magnetico carro",
            "category_hint": "Car Accessories",
            "first_seen_at": "2026-05-24T12:05:00-03:00",
            "last_seen_at": "2026-06-16T09:54:00-03:00",
            "latest_result_count": 910,
            "competition_level": "medium",
            "seasonality_tag": "uptrend",
            "status": "active",
            "notes": "Short conversion path with solid demand.",
        },
        {
            "keyword_uid": "kw_br_4e10c3d7",
            "platform": "AliExpress",
            "market_code": "br",
            "language_code": "pt-BR",
            "normalized_keyword": "mini seladora portatil",
            "original_keyword": "mini seladora portatil",
            "category_hint": "Kitchen Gadgets",
            "first_seen_at": "2026-05-22T13:15:00-03:00",
            "last_seen_at": "2026-06-16T09:57:00-03:00",
            "latest_result_count": 620,
            "competition_level": "low",
            "seasonality_tag": "stable",
            "status": "active",
            "notes": "Low-competition utility keyword.",
        },
    ]

    market_score = [
        {
            "market_score_id": "ms_20260616_001",
            "score_date": "2026-06-16",
            "platform": "Shopee",
            "market_code": "br",
            "keyword_uid": "kw_br_0f4a2b1c",
            "keyword": "organizador cozinha",
            "market_demand_score": 84.0,
            "competition_score": 61.0,
            "price_attractiveness_score": 79.0,
            "trend_score": 81.0,
            "macro_risk_score": 32.0,
            "operation_quality_score": 74.0,
            "total_score": 82.0,
            "score_version": "v0.1",
            "created_at": "2026-06-16T10:10:00-03:00",
            "notes": "Solid home organization demand.",
        },
        {
            "market_score_id": "ms_20260616_002",
            "score_date": "2026-06-16",
            "platform": "Mercado Livre",
            "market_code": "br",
            "keyword_uid": "kw_br_f0b98d22",
            "keyword": "garrafa termica",
            "market_demand_score": 76.0,
            "competition_score": 63.0,
            "price_attractiveness_score": 71.0,
            "trend_score": 68.0,
            "macro_risk_score": 28.0,
            "operation_quality_score": 72.0,
            "total_score": 76.0,
            "score_version": "v0.1",
            "created_at": "2026-06-16T10:10:00-03:00",
            "notes": "Stable drinkware demand.",
        },
        {
            "market_score_id": "ms_20260616_003",
            "score_date": "2026-06-16",
            "platform": "Amazon BR",
            "market_code": "br",
            "keyword_uid": "kw_br_661db203",
            "keyword": "luminaria recarregavel",
            "market_demand_score": 70.0,
            "competition_score": 58.0,
            "price_attractiveness_score": 65.0,
            "trend_score": 77.0,
            "macro_risk_score": 35.0,
            "operation_quality_score": 66.0,
            "total_score": 69.0,
            "score_version": "v0.1",
            "created_at": "2026-06-16T10:10:00-03:00",
            "notes": "Rising demand with moderate risk.",
        },
        {
            "market_score_id": "ms_20260616_004",
            "score_date": "2026-06-16",
            "platform": "TikTok Shop BR",
            "market_code": "br",
            "keyword_uid": "kw_br_202ff870",
            "keyword": "kit skincare viagem",
            "market_demand_score": 88.0,
            "competition_score": 74.0,
            "price_attractiveness_score": 69.0,
            "trend_score": 90.0,
            "macro_risk_score": 41.0,
            "operation_quality_score": 71.0,
            "total_score": 88.0,
            "score_version": "v0.1",
            "created_at": "2026-06-16T10:10:00-03:00",
            "notes": "Strong social momentum with compliance watch.",
        },
        {
            "market_score_id": "ms_20260616_005",
            "score_date": "2026-06-16",
            "platform": "Temu",
            "market_code": "br",
            "keyword_uid": "kw_br_9dc5810e",
            "keyword": "suporte magnetico carro",
            "market_demand_score": 79.0,
            "competition_score": 66.0,
            "price_attractiveness_score": 82.0,
            "trend_score": 73.0,
            "macro_risk_score": 30.0,
            "operation_quality_score": 75.0,
            "total_score": 78.0,
            "score_version": "v0.1",
            "created_at": "2026-06-16T10:10:00-03:00",
            "notes": "Healthy demand with efficient price band.",
        },
        {
            "market_score_id": "ms_20260616_006",
            "score_date": "2026-06-16",
            "platform": "AliExpress",
            "market_code": "br",
            "keyword_uid": "kw_br_4e10c3d7",
            "keyword": "mini seladora portatil",
            "market_demand_score": 68.0,
            "competition_score": 54.0,
            "price_attractiveness_score": 76.0,
            "trend_score": 65.0,
            "macro_risk_score": 29.0,
            "operation_quality_score": 69.0,
            "total_score": 71.0,
            "score_version": "v0.1",
            "created_at": "2026-06-16T10:10:00-03:00",
            "notes": "Utility product with manageable competition.",
        },
    ]

    opportunity_score = [
        {
            "opportunity_score_id": "opp_20260616_001",
            "score_date": "2026-06-16",
            "platform": "Shopee",
            "market_code": "br",
            "keyword_uid": "kw_br_0f4a2b1c",
            "keyword": "organizador cozinha",
            "category_hint": "Home Storage",
            "market_demand_score": 84.0,
            "competition_score": 61.0,
            "profit_score": 83.0,
            "content_gap_score": 76.0,
            "logistics_risk_score": 24.0,
            "policy_risk_score": 18.0,
            "total_score": 91.0,
            "recommendation_level": "A",
            "decision_notes": "需求热度高，标题和主图还有提升空间，适合今天优先复核。",
            "created_at": "2026-06-16T10:20:00-03:00",
        },
        {
            "opportunity_score_id": "opp_20260616_002",
            "score_date": "2026-06-16",
            "platform": "Mercado Livre",
            "market_code": "br",
            "keyword_uid": "kw_br_f0b98d22",
            "keyword": "garrafa termica",
            "category_hint": "Drinkware",
            "market_demand_score": 76.0,
            "competition_score": 63.0,
            "profit_score": 78.0,
            "content_gap_score": 66.0,
            "logistics_risk_score": 19.0,
            "policy_risk_score": 14.0,
            "total_score": 84.0,
            "recommendation_level": "B",
            "decision_notes": "需求稳定，适合做价格带和组合装复核。",
            "created_at": "2026-06-16T10:20:00-03:00",
        },
        {
            "opportunity_score_id": "opp_20260616_003",
            "score_date": "2026-06-16",
            "platform": "Amazon BR",
            "market_code": "br",
            "keyword_uid": "kw_br_661db203",
            "keyword": "luminaria recarregavel",
            "category_hint": "Portable Lighting",
            "market_demand_score": 70.0,
            "competition_score": 58.0,
            "profit_score": 69.0,
            "content_gap_score": 73.0,
            "logistics_risk_score": 27.0,
            "policy_risk_score": 20.0,
            "total_score": 73.0,
            "recommendation_level": "B",
            "decision_notes": "趋势仍在上行，但评论样本偏少，需要先看内容承接。",
            "created_at": "2026-06-16T10:20:00-03:00",
        },
        {
            "opportunity_score_id": "opp_20260616_004",
            "score_date": "2026-06-16",
            "platform": "TikTok Shop BR",
            "market_code": "br",
            "keyword_uid": "kw_br_202ff870",
            "keyword": "kit skincare viagem",
            "category_hint": "Beauty Travel",
            "market_demand_score": 88.0,
            "competition_score": 74.0,
            "profit_score": 72.0,
            "content_gap_score": 84.0,
            "logistics_risk_score": 36.0,
            "policy_risk_score": 44.0,
            "total_score": 89.0,
            "recommendation_level": "A",
            "decision_notes": "流量爆发明显，但合规风险高，必须先走人工审核。",
            "created_at": "2026-06-16T10:20:00-03:00",
        },
        {
            "opportunity_score_id": "opp_20260616_005",
            "score_date": "2026-06-16",
            "platform": "Temu",
            "market_code": "br",
            "keyword_uid": "kw_br_9dc5810e",
            "keyword": "suporte magnetico carro",
            "category_hint": "Car Accessories",
            "market_demand_score": 79.0,
            "competition_score": 66.0,
            "profit_score": 80.0,
            "content_gap_score": 75.0,
            "logistics_risk_score": 31.0,
            "policy_risk_score": 18.0,
            "total_score": 87.0,
            "recommendation_level": "A",
            "decision_notes": "客单价轻、转化链路短，适合今天优先看投放承接。",
            "created_at": "2026-06-16T10:20:00-03:00",
        },
        {
            "opportunity_score_id": "opp_20260616_006",
            "score_date": "2026-06-16",
            "platform": "AliExpress",
            "market_code": "br",
            "keyword_uid": "kw_br_4e10c3d7",
            "keyword": "mini seladora portatil",
            "category_hint": "Kitchen Gadgets",
            "market_demand_score": 68.0,
            "competition_score": 54.0,
            "profit_score": 74.0,
            "content_gap_score": 71.0,
            "logistics_risk_score": 29.0,
            "policy_risk_score": 17.0,
            "total_score": 79.0,
            "recommendation_level": "B",
            "decision_notes": "竞争压力较低，但库存偏紧，适合先确认供给再推进。",
            "created_at": "2026-06-16T10:20:00-03:00",
        },
    ]

    analysis_queue = [
        {
            "analysis_id": "analysis_20260617_001",
            "package_id": "pkg_20260617_001",
            "created_at": "2026-06-17T09:10:00-03:00",
            "analysis_type": "daily_opportunity_scan",
            "platform_scope_json": json.dumps(["Shopee", "Mercado Livre", "Amazon BR"]),
            "date_range_start": "2026-06-16",
            "date_range_end": "2026-06-17",
            "package_path": "data/analysis_packages/analysis_package_20260617_001.json",
            "quality_status": "warning",
            "status": "pending_analysis",
            "priority": 1,
            "requested_questions_json": json.dumps(
                [
                    "今天哪些商品最值得先做人工复核？",
                    "哪些高分机会需要先确认内容和价格带？",
                ]
            ),
            "exported_at": "2026-06-17T09:12:00-03:00",
            "analyzed_at": None,
            "notes": "优先筛出今天应该先看的高分商品。",
        },
        {
            "analysis_id": "analysis_20260617_002",
            "package_id": "pkg_20260617_002",
            "created_at": "2026-06-17T09:20:00-03:00",
            "analysis_type": "risk_gate_review",
            "platform_scope_json": json.dumps(["TikTok Shop BR", "Amazon BR", "Temu"]),
            "date_range_start": "2026-06-17",
            "date_range_end": "2026-06-17",
            "package_path": "data/analysis_packages/analysis_package_20260617_002.json",
            "quality_status": "pass",
            "status": "pending_analysis",
            "priority": 1,
            "requested_questions_json": json.dumps(
                [
                    "哪些机会必须先过人工风控或合规闸门？",
                    "哪些风险会直接拖慢今天的执行？",
                ]
            ),
            "exported_at": "2026-06-17T09:22:00-03:00",
            "analyzed_at": None,
            "notes": "先识别高热度但不能直接推进的风险项。",
        },
        {
            "analysis_id": "analysis_20260617_003",
            "package_id": "pkg_20260617_003",
            "created_at": "2026-06-17T09:35:00-03:00",
            "analysis_type": "category_market_watch",
            "platform_scope_json": json.dumps(["Shopee", "Mercado Livre", "AliExpress"]),
            "date_range_start": "2026-06-17",
            "date_range_end": "2026-06-17",
            "package_path": "data/analysis_packages/analysis_package_20260617_003.json",
            "quality_status": "pass",
            "status": "pending_analysis",
            "priority": 2,
            "requested_questions_json": json.dumps(
                [
                    "哪些类目需求仍在走强？",
                    "哪些类目虽然热，但竞争已经开始抬头？",
                ]
            ),
            "exported_at": "2026-06-17T09:37:00-03:00",
            "analyzed_at": None,
            "notes": "补充市场层对类目需求、竞争和趋势的判断。",
        },
        {
            "analysis_id": "analysis_20260617_004",
            "package_id": "pkg_20260617_004",
            "created_at": "2026-06-17T09:50:00-03:00",
            "analysis_type": "manual_approval_precheck",
            "platform_scope_json": json.dumps(["Shopee", "TikTok Shop BR", "Amazon BR"]),
            "date_range_start": "2026-06-17",
            "date_range_end": "2026-06-17",
            "package_path": "data/analysis_packages/analysis_package_20260617_004.json",
            "quality_status": "warning",
            "status": "pending_analysis",
            "priority": 2,
            "requested_questions_json": json.dumps(
                [
                    "哪些建议最值得今天先进入人工审批？",
                    "哪些项适合留在观察队列，不急着推进？",
                ]
            ),
            "exported_at": "2026-06-17T09:52:00-03:00",
            "analyzed_at": None,
            "notes": "为人工审批前置整理建议优先级。",
        },
        {
            "analysis_id": "analysis_20260617_005",
            "package_id": "pkg_20260617_005",
            "created_at": "2026-06-17T10:05:00-03:00",
            "analysis_type": "inventory_and_supply_watch",
            "platform_scope_json": json.dumps(["TikTok Shop BR", "AliExpress"]),
            "date_range_start": "2026-06-17",
            "date_range_end": "2026-06-17",
            "package_path": "data/analysis_packages/analysis_package_20260617_005.json",
            "quality_status": "pass",
            "status": "pending_analysis",
            "priority": 2,
            "requested_questions_json": json.dumps(
                [
                    "哪些高分商品需要先确认供给窗口？",
                    "哪些品适合先看库存，再决定是否提级？",
                ]
            ),
            "exported_at": "2026-06-17T10:07:00-03:00",
            "analyzed_at": None,
            "notes": "优先识别供给偏紧但机会分仍高的商品。",
        },
        {
            "analysis_id": "analysis_20260617_006",
            "package_id": "pkg_20260617_006",
            "created_at": "2026-06-17T10:18:00-03:00",
            "analysis_type": "content_gap_watch",
            "platform_scope_json": json.dumps(["Amazon BR", "Temu"]),
            "date_range_start": "2026-06-17",
            "date_range_end": "2026-06-17",
            "package_path": "data/analysis_packages/analysis_package_20260617_006.json",
            "quality_status": "pass",
            "status": "pending_analysis",
            "priority": 3,
            "requested_questions_json": json.dumps(
                [
                    "哪些机会品的评论和内容样本还不够？",
                    "今天哪些项更适合保留观察，而不是立即推进？",
                ]
            ),
            "exported_at": "2026-06-17T10:20:00-03:00",
            "analyzed_at": None,
            "notes": "持续观察需要补内容和样本的机会项。",
        },
    ]

    action_queue = [
        {
            "action_id": "act_20260617_001",
            "package_id": "pkg_20260617_001",
            "created_at": "2026-06-17T09:18:00-03:00",
            "platform": "TikTok Shop BR",
            "market_code": "br",
            "target_type": "listing",
            "target_id": "prod_97c41f03",
            "action_type": "listing_review",
            "before_value_json": json.dumps({"compliance_status": "unknown"}),
            "after_value_json": json.dumps({"requested_review": "beauty_compliance_manual_check"}),
            "recommendation_text": "高热度商品先做人工合规复核，再决定是否进入后续审批。",
            "confidence_score": 0.86,
            "risk_level": "high",
            "need_approval": 1,
            "approval_status": "pending_review",
            "status": "pending_review",
            "approved_by": None,
            "approved_at": None,
            "executed_at": None,
            "execution_result": None,
            "error_log": None,
        },
        {
            "action_id": "act_20260617_002",
            "package_id": "pkg_20260617_002",
            "created_at": "2026-06-17T09:26:00-03:00",
            "platform": "Shopee",
            "market_code": "br",
            "target_type": "product",
            "target_id": "prod_8fd1a2c0",
            "action_type": "title_review",
            "before_value_json": json.dumps({"title_current": "Organizador de Cozinha Modular"}),
            "after_value_json": json.dumps({"title_candidate": "Organizador Modular para Cozinha Compacta"}),
            "recommendation_text": "先人工复核标题方向和主卖点，再决定是否推进。",
            "confidence_score": 0.83,
            "risk_level": "medium",
            "need_approval": 1,
            "approval_status": "pending_review",
            "status": "pending_review",
            "approved_by": None,
            "approved_at": None,
            "executed_at": None,
            "execution_result": None,
            "error_log": None,
        },
        {
            "action_id": "act_20260617_003",
            "package_id": "pkg_20260617_003",
            "created_at": "2026-06-17T09:42:00-03:00",
            "platform": "Mercado Livre",
            "market_code": "br",
            "target_type": "product",
            "target_id": "prod_7bb2f310",
            "action_type": "price_review",
            "before_value_json": json.dumps({"price_amount": 58.5}),
            "after_value_json": json.dumps({"suggested_price_amount": 56.9}),
            "recommendation_text": "建议先人工确认价格带，不直接改价。",
            "confidence_score": 0.67,
            "risk_level": "low",
            "need_approval": 1,
            "approval_status": "approved_local",
            "status": "approved_local",
            "approved_by": "Ana",
            "approved_at": "2026-06-17T10:06:00-03:00",
            "executed_at": None,
            "execution_result": None,
            "error_log": None,
        },
        {
            "action_id": "act_20260617_004",
            "package_id": "pkg_20260617_004",
            "created_at": "2026-06-17T10:02:00-03:00",
            "platform": "Amazon BR",
            "market_code": "br",
            "target_type": "product",
            "target_id": "prod_2c0d88aa",
            "action_type": "image_review",
            "before_value_json": json.dumps({"hero_image_status": "draft"}),
            "after_value_json": json.dumps({"requested_review": "manual_image_direction_review"}),
            "recommendation_text": "主图方向需要先人工判断，当前不适合推进。",
            "confidence_score": 0.71,
            "risk_level": "medium",
            "need_approval": 1,
            "approval_status": "rejected_local",
            "status": "rejected_local",
            "approved_by": "Marina",
            "approved_at": "2026-06-17T10:18:00-03:00",
            "executed_at": None,
            "execution_result": None,
            "error_log": None,
        },
        {
            "action_id": "act_20260617_005",
            "package_id": "pkg_20260617_005",
            "created_at": "2026-06-17T10:15:00-03:00",
            "platform": "AliExpress",
            "market_code": "br",
            "target_type": "listing",
            "target_id": "prod_f42ab991",
            "action_type": "listing_review",
            "before_value_json": json.dumps({"inventory_status": "low_stock"}),
            "after_value_json": json.dumps({"requested_review": "supply_window_validation"}),
            "recommendation_text": "库存偏紧，建议延后处理，先确认供给窗口。",
            "confidence_score": 0.73,
            "risk_level": "medium",
            "need_approval": 1,
            "approval_status": "deferred_local",
            "status": "deferred_local",
            "approved_by": "Joao",
            "approved_at": "2026-06-17T10:24:00-03:00",
            "executed_at": None,
            "execution_result": None,
            "error_log": None,
        },
        {
            "action_id": "act_20260617_006",
            "package_id": "pkg_20260617_006",
            "created_at": "2026-06-17T10:28:00-03:00",
            "platform": "Temu",
            "market_code": "br",
            "target_type": "product",
            "target_id": "prod_5d4e1c7b",
            "action_type": "title_review",
            "before_value_json": json.dumps({"title_current": "Suporte Magnetico para Celular no Carro"}),
            "after_value_json": json.dumps({"requested_review": "manual_ad_copy_alignment"}),
            "recommendation_text": "建议先人工确认投放承接文案，再决定是否推进。",
            "confidence_score": 0.79,
            "risk_level": "medium",
            "need_approval": 1,
            "approval_status": "pending_review",
            "status": "pending_review",
            "approved_by": None,
            "approved_at": None,
            "executed_at": None,
            "execution_result": None,
            "error_log": None,
        },
        {
            "action_id": "exec_20260618_purchase_001",
            "package_id": "action_execution_layer",
            "created_at": "2026-06-18T08:15:00-03:00",
            "platform": "Shopee",
            "market_code": "br",
            "product_id": "ITEM-001",
            "target_type": "execution_action",
            "target_id": "ITEM-001",
            "action_type": "purchase",
            "suggested_by": "decisionEngine",
            "before_value_json": None,
            "after_value_json": json.dumps(
                {
                    "product_uid": "product_shopee_br_ITEM-001",
                    "suggested_by": "decisionEngine",
                    "requested_by": "operator@local.br",
                    "notes": "来自库存断货风险和机会评分的组合建议。",
                }
            ),
            "recommendation_text": "模拟采购后可覆盖 14 天销量，预计降低断货风险，但会占用现金流。",
            "confidence_score": 0.72,
            "risk_level": "medium",
            "need_approval": 1,
            "approval_status": "pending",
            "status": "pending",
            "approved_by": None,
            "approved_at": None,
            "executed_at": None,
            "execution_result": None,
            "error_log": None,
            "simulate_result": "模拟采购后可覆盖 14 天销量，预计降低断货风险，但会占用现金流。",
            "expected_profit_change": 4200.0,
            "expected_risk_change": -0.08,
        },
        {
            "action_id": "exec_20260618_price_002",
            "package_id": "action_execution_layer",
            "created_at": "2026-06-18T08:25:00-03:00",
            "platform": "Shopee",
            "market_code": "br",
            "product_id": "ITEM-002",
            "target_type": "execution_action",
            "target_id": "ITEM-002",
            "action_type": "price",
            "suggested_by": "taskSystem",
            "before_value_json": None,
            "after_value_json": json.dumps(
                {
                    "product_uid": "product_shopee_br_ITEM-002",
                    "suggested_by": "taskSystem",
                    "requested_by": "operator@local.br",
                    "notes": "利润中心提示毛利偏低，仅模拟审批通过。",
                }
            ),
            "recommendation_text": "模拟价格调整后预计利润改善，但需人工确认不会伤害转化。",
            "confidence_score": 0.72,
            "risk_level": "medium",
            "need_approval": 1,
            "approval_status": "approved",
            "status": "approved",
            "approved_by": "admin@local.br",
            "approved_at": "2026-06-18T08:40:00-03:00",
            "executed_at": None,
            "execution_result": None,
            "error_log": None,
            "simulate_result": "模拟价格调整后预计利润改善，但需人工确认不会伤害转化。",
            "expected_profit_change": 2600.0,
            "expected_risk_change": 0.04,
        },
        {
            "action_id": "exec_20260618_ad_003",
            "package_id": "action_execution_layer",
            "created_at": "2026-06-18T08:35:00-03:00",
            "platform": "Amazon BR",
            "market_code": "br",
            "product_id": "AMZ-005",
            "target_type": "execution_action",
            "target_id": "AMZ-005",
            "action_type": "ad",
            "suggested_by": "taskSystem",
            "before_value_json": None,
            "after_value_json": json.dumps(
                {
                    "product_uid": "product_amazon_br_AMZ-005",
                    "suggested_by": "taskSystem",
                    "requested_by": "operator@local.br",
                    "notes": "财务认为当前现金流压力较高，暂不批准。",
                }
            ),
            "recommendation_text": "模拟广告预算调整后预计带来增量利润，但 ACOS 风险略升。",
            "confidence_score": 0.72,
            "risk_level": "high",
            "need_approval": 1,
            "approval_status": "rejected",
            "status": "rejected",
            "approved_by": "finance@local.br",
            "approved_at": "2026-06-18T08:55:00-03:00",
            "executed_at": None,
            "execution_result": None,
            "error_log": None,
            "simulate_result": "模拟广告预算调整后预计带来增量利润，但 ACOS 风险略升。",
            "expected_profit_change": 1500.0,
            "expected_risk_change": 0.06,
        },
        {
            "action_id": "exec_20260618_listing_004",
            "package_id": "action_execution_layer",
            "created_at": "2026-06-18T09:05:00-03:00",
            "platform": "TikTok Shop BR",
            "market_code": "br",
            "product_id": "TT-006",
            "target_type": "execution_action",
            "target_id": "TT-006",
            "action_type": "listing",
            "suggested_by": "decisionEngine",
            "before_value_json": None,
            "after_value_json": json.dumps(
                {
                    "product_uid": "product_tiktok_br_TT-006",
                    "suggested_by": "decisionEngine",
                    "requested_by": "operator@local.br",
                    "notes": "内容建议来自 Analysis Center，必须人工审批。",
                }
            ),
            "recommendation_text": "模拟商品内容优化后预计提升转化，不会自动上架或修改平台内容。",
            "confidence_score": 0.72,
            "risk_level": "medium",
            "need_approval": 1,
            "approval_status": "pending",
            "status": "pending",
            "approved_by": None,
            "approved_at": None,
            "executed_at": None,
            "execution_result": None,
            "error_log": None,
            "simulate_result": "模拟商品内容优化后预计提升转化，不会自动上架或修改平台内容。",
            "expected_profit_change": 950.0,
            "expected_risk_change": -0.03,
        },
    ]

    action_history = [
        {
            "history_id": "history_exec_20260618_price_002_created",
            "action_id": "exec_20260618_price_002",
            "action": "created",
            "actor_role": "operator",
            "actor_name": "operator@local.br",
            "previous_status": None,
            "new_status": "pending",
            "notes": "operator 发起价格类执行申请。",
            "created_at": "2026-06-18T08:25:00-03:00",
            "simulate_result": "模拟价格调整后预计利润改善，但需人工确认不会伤害转化。",
        },
        {
            "history_id": "history_exec_20260618_price_002_approved",
            "action_id": "exec_20260618_price_002",
            "action": "approved",
            "actor_role": "admin",
            "actor_name": "admin@local.br",
            "previous_status": "pending",
            "new_status": "approved",
            "notes": "admin 批准模拟执行申请。未连接任何平台写 API。",
            "created_at": "2026-06-18T08:40:00-03:00",
            "simulate_result": "模拟价格调整后预计利润改善，但需人工确认不会伤害转化。",
        },
        {
            "history_id": "history_exec_20260618_ad_003_rejected",
            "action_id": "exec_20260618_ad_003",
            "action": "rejected",
            "actor_role": "finance",
            "actor_name": "finance@local.br",
            "previous_status": "pending",
            "new_status": "rejected",
            "notes": "finance 驳回成本类广告动作。未执行真实广告操作。",
            "created_at": "2026-06-18T08:55:00-03:00",
            "simulate_result": "模拟广告预算调整后预计带来增量利润，但 ACOS 风险略升。",
        },
    ]

    approval_history = [
        {
            "history_id": "hist_act_20260617_003_20260617100600",
            "approval_id": "act_20260617_003",
            "action": "approved_local",
            "reviewer": "Ana",
            "reviewed_at": "2026-06-17T10:06:00-03:00",
            "notes": "先进入人工价格复核，不执行真实调价。",
        },
        {
            "history_id": "hist_act_20260617_004_20260617101800",
            "approval_id": "act_20260617_004",
            "action": "rejected_local",
            "reviewer": "Marina",
            "reviewed_at": "2026-06-17T10:18:00-03:00",
            "notes": "样本不足，先不推进主图变更建议。",
        },
        {
            "history_id": "hist_act_20260617_005_20260617102400",
            "approval_id": "act_20260617_005",
            "action": "deferred_local",
            "reviewer": "Joao",
            "reviewed_at": "2026-06-17T10:24:00-03:00",
            "notes": "等补货确认后再回到审批队列。",
        },
    ]

    permissions = [
        {
            "permission_id": "perm_dashboard_view",
            "permission_key": "dashboard:view",
            "resource": "dashboard",
            "action": "view",
            "description": "View CEO dashboard.",
            "created_at": "2026-06-17T09:00:00-03:00",
        },
        {
            "permission_id": "perm_command_center_view",
            "permission_key": "command_center:view",
            "resource": "command_center",
            "action": "view",
            "description": "View internal command center.",
            "created_at": "2026-06-19T10:00:00-03:00",
        },
        {
            "permission_id": "perm_tenants_view",
            "permission_key": "tenants:view",
            "resource": "tenants",
            "action": "view",
            "description": "View tenants, workspaces, plan status, and usage.",
            "created_at": "2026-06-19T09:00:00-03:00",
        },
        {
            "permission_id": "perm_tasks_view",
            "permission_key": "tasks:view",
            "resource": "tasks",
            "action": "view",
            "description": "View today task center.",
            "created_at": "2026-06-17T09:00:00-03:00",
        },
        {
            "permission_id": "perm_opportunities_view",
            "permission_key": "opportunities:view",
            "resource": "opportunities",
            "action": "view",
            "description": "View opportunities center.",
            "created_at": "2026-06-17T09:00:00-03:00",
        },
        {
            "permission_id": "perm_analysis_view",
            "permission_key": "analysis:view",
            "resource": "analysis",
            "action": "view",
            "description": "View analysis center.",
            "created_at": "2026-06-17T09:00:00-03:00",
        },
        {
            "permission_id": "perm_approvals_view",
            "permission_key": "approvals:view",
            "resource": "approvals",
            "action": "view",
            "description": "View approval center.",
            "created_at": "2026-06-17T09:00:00-03:00",
        },
        {
            "permission_id": "perm_approvals_approve",
            "permission_key": "approvals:approve",
            "resource": "approvals",
            "action": "approve",
            "description": "Approve or reject local recommendations.",
            "created_at": "2026-06-17T09:00:00-03:00",
        },
        {
            "permission_id": "perm_actions_view",
            "permission_key": "actions:view",
            "resource": "actions",
            "action": "view",
            "description": "View action execution guard layer.",
            "created_at": "2026-06-17T09:00:00-03:00",
        },
        {
            "permission_id": "perm_actions_approve",
            "permission_key": "actions:approve",
            "resource": "actions",
            "action": "approve",
            "description": "Approve or reject local execution requests.",
            "created_at": "2026-06-17T09:00:00-03:00",
        },
        {
            "permission_id": "perm_profit_view",
            "permission_key": "profit:view",
            "resource": "profit",
            "action": "view",
            "description": "View profit center.",
            "created_at": "2026-06-17T09:00:00-03:00",
        },
        {
            "permission_id": "perm_inventory_view",
            "permission_key": "inventory:view",
            "resource": "inventory",
            "action": "view",
            "description": "View inventory center.",
            "created_at": "2026-06-17T09:00:00-03:00",
        },
        {
            "permission_id": "perm_shopee_view",
            "permission_key": "shopee:view",
            "resource": "shopee",
            "action": "view",
            "description": "View Shopee read-only connector.",
            "created_at": "2026-06-17T09:00:00-03:00",
        },
        {
            "permission_id": "perm_decision_feedback_view",
            "permission_key": "decision_feedback:view",
            "resource": "decision_feedback",
            "action": "view",
            "description": "View decision feedback loop.",
            "created_at": "2026-06-17T09:00:00-03:00",
        },
        {
            "permission_id": "perm_business_impact_view",
            "permission_key": "business_impact:view",
            "resource": "business_impact",
            "action": "view",
            "description": "View business impact analytics.",
            "created_at": "2026-06-17T09:00:00-03:00",
        },
        {
            "permission_id": "perm_self_optimization_view",
            "permission_key": "self_optimization:view",
            "resource": "self_optimization",
            "action": "view",
            "description": "View self-optimization recommendations.",
            "created_at": "2026-06-17T09:00:00-03:00",
        },
        {
            "permission_id": "perm_daily_ops_view",
            "permission_key": "daily_ops:view",
            "resource": "daily_ops",
            "action": "view",
            "description": "View daily operations control center.",
            "created_at": "2026-06-17T09:00:00-03:00",
        },
        {
            "permission_id": "perm_verification_view",
            "permission_key": "verification:view",
            "resource": "verification",
            "action": "view",
            "description": "View verification center.",
            "created_at": "2026-06-17T09:00:00-03:00",
        },
        {
            "permission_id": "perm_users_view",
            "permission_key": "users:view",
            "resource": "users",
            "action": "view",
            "description": "View users and permissions.",
            "created_at": "2026-06-17T09:00:00-03:00",
        },
        {
            "permission_id": "perm_users_manage",
            "permission_key": "users:manage",
            "resource": "users",
            "action": "manage",
            "description": "Create and edit local users.",
            "created_at": "2026-06-17T09:00:00-03:00",
        },
        {
            "permission_id": "perm_system_view",
            "permission_key": "system:view",
            "resource": "system",
            "action": "view",
            "description": "View system status.",
            "created_at": "2026-06-17T09:00:00-03:00",
        },
        {
            "permission_id": "perm_system_health_view",
            "permission_key": "system_health:view",
            "resource": "system_health",
            "action": "view",
            "description": "View system health checks.",
            "created_at": "2026-06-17T09:00:00-03:00",
        },
    ]

    all_permission_keys = [row["permission_key"] for row in permissions]
    view_permission_keys = [row["permission_key"] for row in permissions if row["action"] == "view"]
    operator_permission_keys = [
        "dashboard:view",
        "command_center:view",
        "tenants:view",
        "tasks:view",
        "opportunities:view",
        "analysis:view",
        "approvals:view",
        "approvals:approve",
        "actions:view",
        "shopee:view",
        "decision_feedback:view",
        "business_impact:view",
        "self_optimization:view",
        "daily_ops:view",
        "verification:view",
    ]
    finance_permission_keys = [
        "dashboard:view",
        "command_center:view",
        "tenants:view",
        "daily_ops:view",
        "profit:view",
        "actions:view",
        "actions:approve",
        "business_impact:view",
        "self_optimization:view",
        "verification:view",
    ]

    roles = [
        {
            "role_id": "admin",
            "role_name": "admin",
            "description": "Full local system permission.",
            "is_system": 1,
            "permission_keys_json": json.dumps(all_permission_keys),
            "created_at": "2026-06-17T09:00:00-03:00",
        },
        {
            "role_id": "operator",
            "role_name": "operator",
            "description": "Dashboard, tasks, opportunities, analysis, approvals.",
            "is_system": 1,
            "permission_keys_json": json.dumps(operator_permission_keys),
            "created_at": "2026-06-17T09:05:00-03:00",
        },
        {
            "role_id": "buyer",
            "role_name": "buyer",
            "description": "Dashboard, tasks, inventory.",
            "is_system": 1,
            "permission_keys_json": json.dumps(["dashboard:view", "command_center:view", "tenants:view", "daily_ops:view", "tasks:view", "inventory:view", "verification:view"]),
            "created_at": "2026-06-17T09:10:00-03:00",
        },
        {
            "role_id": "finance",
            "role_name": "finance",
            "description": "Dashboard, profit, and cost action approval.",
            "is_system": 1,
            "permission_keys_json": json.dumps(finance_permission_keys),
            "created_at": "2026-06-17T09:15:00-03:00",
        },
        {
            "role_id": "viewer",
            "role_name": "viewer",
            "description": "Read-only access.",
            "is_system": 1,
            "permission_keys_json": json.dumps(view_permission_keys),
            "created_at": "2026-06-17T09:20:00-03:00",
        },
    ]

    users = [
        {
            "user_id": "user_admin_001",
            "email": "admin@local.br",
            "display_name": "Admin Local",
            "status": "active",
            "default_role": "admin",
            "last_login_at": "2026-06-17T09:30:00-03:00",
            "created_at": "2026-06-17T09:00:00-03:00",
            "updated_at": "2026-06-17T09:00:00-03:00",
        },
        {
            "user_id": "user_operator_001",
            "email": "operator@local.br",
            "display_name": "Operador Local",
            "status": "active",
            "default_role": "operator",
            "last_login_at": "2026-06-17T09:35:00-03:00",
            "created_at": "2026-06-17T09:05:00-03:00",
            "updated_at": "2026-06-17T09:05:00-03:00",
        },
        {
            "user_id": "user_buyer_001",
            "email": "buyer@local.br",
            "display_name": "Compras Local",
            "status": "active",
            "default_role": "buyer",
            "last_login_at": "2026-06-17T09:40:00-03:00",
            "created_at": "2026-06-17T09:10:00-03:00",
            "updated_at": "2026-06-17T09:10:00-03:00",
        },
        {
            "user_id": "user_finance_001",
            "email": "finance@local.br",
            "display_name": "Financeiro Local",
            "status": "active",
            "default_role": "finance",
            "last_login_at": "2026-06-17T09:45:00-03:00",
            "created_at": "2026-06-17T09:15:00-03:00",
            "updated_at": "2026-06-17T09:15:00-03:00",
        },
        {
            "user_id": "user_viewer_001",
            "email": "viewer@local.br",
            "display_name": "Viewer Local",
            "status": "active",
            "default_role": "viewer",
            "last_login_at": None,
            "created_at": "2026-06-17T09:20:00-03:00",
            "updated_at": "2026-06-17T09:20:00-03:00",
        },
    ]

    user_roles = [
        {"user_id": "user_admin_001", "role_id": "admin", "assigned_at": "2026-06-17T09:00:00-03:00", "assigned_by": "system"},
        {"user_id": "user_operator_001", "role_id": "operator", "assigned_at": "2026-06-17T09:05:00-03:00", "assigned_by": "user_admin_001"},
        {"user_id": "user_buyer_001", "role_id": "buyer", "assigned_at": "2026-06-17T09:10:00-03:00", "assigned_by": "user_admin_001"},
        {"user_id": "user_finance_001", "role_id": "finance", "assigned_at": "2026-06-17T09:15:00-03:00", "assigned_by": "user_admin_001"},
        {"user_id": "user_viewer_001", "role_id": "viewer", "assigned_at": "2026-06-17T09:20:00-03:00", "assigned_by": "user_admin_001"},
    ]

    tenant_users = [
        {"tenant_id": "demo_tenant", "user_id": "user_admin_001", "role": "owner"},
        {"tenant_id": "demo_tenant", "user_id": "user_operator_001", "role": "operator"},
        {"tenant_id": "demo_tenant", "user_id": "user_buyer_001", "role": "operator"},
        {"tenant_id": "demo_tenant", "user_id": "user_finance_001", "role": "admin"},
        {"tenant_id": "demo_tenant", "user_id": "user_viewer_001", "role": "viewer"},
        {"tenant_id": "growth_tenant", "user_id": "user_viewer_001", "role": "viewer"},
    ]

    operation_logs = [
        {
            "log_id": "oplog_20260617_login_001",
            "action_type": "login",
            "actor_user_id": "user_admin_001",
            "actor_email": "admin@local.br",
            "target_type": "session",
            "target_id": "local_session_admin",
            "summary": "Admin Local logged into the local system.",
            "status": "success",
            "created_at": "2026-06-17T09:30:00-03:00",
            "metadata_json": json.dumps({"mode": "local"}),
        },
        {
            "log_id": "oplog_20260617_logout_001",
            "action_type": "logout",
            "actor_user_id": "user_operator_001",
            "actor_email": "operator@local.br",
            "target_type": "session",
            "target_id": "local_session_operator",
            "summary": "Operador Local logged out of the local system.",
            "status": "success",
            "created_at": "2026-06-17T09:50:00-03:00",
            "metadata_json": json.dumps({"mode": "local"}),
        },
        {
            "log_id": "oplog_20260617_approval_001",
            "action_type": "approval",
            "actor_user_id": "user_operator_001",
            "actor_email": "operator@local.br",
            "target_type": "action_queue",
            "target_id": "act_20260617_003",
            "summary": "Local approval status updated to approved_local.",
            "status": "success",
            "created_at": "2026-06-17T10:06:00-03:00",
            "metadata_json": json.dumps({"status": "approved_local"}),
        },
        {
            "log_id": "oplog_20260617_user_create_001",
            "action_type": "user_create",
            "actor_user_id": "user_admin_001",
            "actor_email": "admin@local.br",
            "target_type": "users",
            "target_id": "user_viewer_001",
            "summary": "Created local viewer user.",
            "status": "success",
            "created_at": "2026-06-17T09:20:00-03:00",
            "metadata_json": json.dumps({"role": "viewer"}),
        },
        {
            "log_id": "oplog_20260617_user_update_001",
            "action_type": "user_update",
            "actor_user_id": "user_admin_001",
            "actor_email": "admin@local.br",
            "target_type": "users",
            "target_id": "user_operator_001",
            "summary": "Updated local operator user profile.",
            "status": "success",
            "created_at": "2026-06-17T10:12:00-03:00",
            "metadata_json": json.dumps({"role": "operator"}),
        },
    ]

    shopee_orders = [
        {
            "order_id": "shp_order_20260617_001",
            "product_id": "shp_prod_001",
            "sku": "ORG-COZ-MOD-001",
            "quantity": 2,
            "price": 39.9,
            "order_status": "ready_to_ship",
            "created_at": "2026-06-17T08:40:00-03:00",
            "synced_at": "2026-06-17T11:45:00-03:00",
        },
        {
            "order_id": "shp_order_20260617_002",
            "product_id": "shp_prod_002",
            "sku": "SEL-PORT-002",
            "quantity": 1,
            "price": 22.8,
            "order_status": "shipped",
            "created_at": "2026-06-17T09:15:00-03:00",
            "synced_at": "2026-06-17T11:45:00-03:00",
        },
        {
            "order_id": "shp_order_20260617_003",
            "product_id": "shp_prod_003",
            "sku": "SUP-CAR-003",
            "quantity": 3,
            "price": 29.9,
            "order_status": "paid",
            "created_at": "2026-06-17T10:05:00-03:00",
            "synced_at": "2026-06-17T11:45:00-03:00",
        },
    ]

    shopee_products = [
        {
            "product_id": "shp_prod_001",
            "title": "Organizador de Cozinha Modular",
            "price": 39.9,
            "stock": 164,
            "sales_count": 1240,
            "synced_at": "2026-06-17T11:45:00-03:00",
        },
        {
            "product_id": "shp_prod_002",
            "title": "Mini Seladora Portatil para Embalagem",
            "price": 22.8,
            "stock": 24,
            "sales_count": 430,
            "synced_at": "2026-06-17T11:45:00-03:00",
        },
        {
            "product_id": "shp_prod_003",
            "title": "Suporte Magnetico para Celular no Carro",
            "price": 29.9,
            "stock": 410,
            "sales_count": 980,
            "synced_at": "2026-06-17T11:45:00-03:00",
        },
    ]

    shopee_inventory = [
        {
            "product_id": "shp_prod_001",
            "available_stock": 150,
            "reserved_stock": 14,
            "synced_at": "2026-06-17T11:45:00-03:00",
        },
        {
            "product_id": "shp_prod_002",
            "available_stock": 21,
            "reserved_stock": 3,
            "synced_at": "2026-06-17T11:45:00-03:00",
        },
        {
            "product_id": "shp_prod_003",
            "available_stock": 382,
            "reserved_stock": 28,
            "synced_at": "2026-06-17T11:45:00-03:00",
        },
    ]

    decision_feedback = [
        {
            "decision_id": "decision_20260615_sku001",
            "product_id": "ITEM-001",
            "product_uid": "product_shopee_br_ITEM-001",
            "platform": "Shopee",
            "decision_state": "RECOMMEND",
            "user_action": "buy",
            "timestamp": "2026-06-15T09:20:00-03:00",
            "source": "shopee",
            "created_at": "2026-06-15T09:21:00-03:00",
        },
        {
            "decision_id": "decision_20260615_sku002",
            "product_id": "ITEM-002",
            "product_uid": "product_shopee_br_ITEM-002",
            "platform": "Shopee",
            "decision_state": "BLOCKED",
            "user_action": "reject",
            "timestamp": "2026-06-15T10:05:00-03:00",
            "source": "manual",
            "created_at": "2026-06-15T10:07:00-03:00",
        },
        {
            "decision_id": "decision_20260616_sku003",
            "product_id": "ITEM-003",
            "product_uid": "product_shopee_br_ITEM-003",
            "platform": "Shopee",
            "decision_state": "OBSERVE",
            "user_action": "observe",
            "timestamp": "2026-06-16T11:30:00-03:00",
            "source": "shopee",
            "created_at": "2026-06-16T11:31:00-03:00",
        },
        {
            "decision_id": "decision_20260616_sku004",
            "product_id": "MLB-004",
            "product_uid": "product_ml_br_MLB-004",
            "platform": "Mercado Livre",
            "decision_state": "RECOMMEND",
            "user_action": "ignore",
            "timestamp": "2026-06-16T12:10:00-03:00",
            "source": "manual",
            "created_at": "2026-06-16T12:12:00-03:00",
        },
        {
            "decision_id": "decision_20260617_sku005",
            "product_id": "AMZ-005",
            "product_uid": "product_amazon_br_AMZ-005",
            "platform": "Amazon BR",
            "decision_state": "LOCKED",
            "user_action": "buy",
            "timestamp": "2026-06-17T08:40:00-03:00",
            "source": "manual",
            "created_at": "2026-06-17T08:41:00-03:00",
        },
        {
            "decision_id": "decision_20260617_sku006",
            "product_id": "TT-006",
            "product_uid": "product_tiktok_br_TT-006",
            "platform": "TikTok Shop BR",
            "decision_state": "BLOCKED",
            "user_action": "ignore",
            "timestamp": "2026-06-17T09:15:00-03:00",
            "source": "manual",
            "created_at": "2026-06-17T09:16:00-03:00",
        },
    ]

    decision_business_outcomes = [
        {
            "outcome_id": "outcome_decision_20260615_sku001",
            "decision_id": "decision_20260615_sku001",
            "actual_sales": 128,
            "actual_profit": 3840.0,
            "roi_real": 1.46,
            "stock_change": -128,
            "conversion_rate": 0.041,
            "recorded_at": "2026-06-17T18:00:00-03:00",
        },
        {
            "outcome_id": "outcome_decision_20260615_sku002",
            "decision_id": "decision_20260615_sku002",
            "actual_sales": 8,
            "actual_profit": -260.0,
            "roi_real": 0.78,
            "stock_change": -8,
            "conversion_rate": 0.011,
            "recorded_at": "2026-06-17T18:10:00-03:00",
        },
        {
            "outcome_id": "outcome_decision_20260616_sku003",
            "decision_id": "decision_20260616_sku003",
            "actual_sales": 42,
            "actual_profit": 620.0,
            "roi_real": 1.09,
            "stock_change": -42,
            "conversion_rate": 0.027,
            "recorded_at": "2026-06-17T18:12:00-03:00",
        },
        {
            "outcome_id": "outcome_decision_20260616_sku004",
            "decision_id": "decision_20260616_sku004",
            "actual_sales": 18,
            "actual_profit": 90.0,
            "roi_real": 0.96,
            "stock_change": -18,
            "conversion_rate": 0.017,
            "recorded_at": "2026-06-17T18:18:00-03:00",
        },
        {
            "outcome_id": "outcome_decision_20260617_sku005",
            "decision_id": "decision_20260617_sku005",
            "actual_sales": 76,
            "actual_profit": 2140.0,
            "roi_real": 1.31,
            "stock_change": -76,
            "conversion_rate": 0.036,
            "recorded_at": "2026-06-17T19:00:00-03:00",
        },
        {
            "outcome_id": "outcome_decision_20260617_sku006",
            "decision_id": "decision_20260617_sku006",
            "actual_sales": 0,
            "actual_profit": 0.0,
            "roi_real": 0.72,
            "stock_change": 0,
            "conversion_rate": 0.006,
            "recorded_at": "2026-06-17T19:05:00-03:00",
        },
    ]

    for outcome in decision_business_outcomes:
        actual_profit = float(outcome.get("actual_profit") or 0)
        roi_real = float(outcome.get("roi_real") or 0)
        outcome["is_profitable"] = 1 if actual_profit > 0 and roi_real >= 1 else 0
        outcome["is_failed"] = 1 if actual_profit <= 0 or roi_real < 1 else 0

    outcome_by_decision_id = {
        str(outcome["decision_id"]): outcome for outcome in decision_business_outcomes
    }
    decision_history = []
    for feedback in decision_feedback:
        outcome = outcome_by_decision_id.get(str(feedback["decision_id"]))
        decision_history.append(
            {
                "history_id": f"history_{feedback['decision_id']}",
                "decision_id": feedback["decision_id"],
                "product_id": feedback["product_id"],
                "product_uid": feedback["product_uid"],
                "platform": feedback["platform"],
                "decision_state": feedback["decision_state"],
                "user_action": feedback["user_action"],
                "timestamp": feedback["timestamp"],
                "is_profitable": outcome.get("is_profitable") if outcome else None,
                "is_failed": outcome.get("is_failed") if outcome else None,
                "roi_real": outcome.get("roi_real") if outcome else None,
                "source": feedback["source"],
                "created_at": feedback["created_at"],
            }
        )

    decision_learning_adjustments = [
        {
            "adjustment_id": "decision_learning_profit_weight_20260617",
            "adjustment_type": "scoring_weight",
            "target_key": "profit_score_weight",
            "previous_value": 0.32,
            "suggested_value": 0.32,
            "reason": "Seed baseline: profit accuracy is currently stable.",
            "generated_at": "2026-06-17T19:10:00-03:00",
        },
        {
            "adjustment_id": "decision_learning_roi_weight_20260617",
            "adjustment_type": "scoring_weight",
            "target_key": "roi_score_weight",
            "previous_value": 0.20,
            "suggested_value": 0.20,
            "reason": "Seed baseline: ROI deviation is monitored before automatic weight changes.",
            "generated_at": "2026-06-17T19:10:00-03:00",
        },
        {
            "adjustment_id": "decision_learning_block_weight_20260617",
            "adjustment_type": "decision_bias",
            "target_key": "blocked_strictness",
            "previous_value": 0.24,
            "suggested_value": 0.24,
            "reason": "Seed baseline: BLOCKED accuracy is reviewed by humans before execution.",
            "generated_at": "2026-06-17T19:10:00-03:00",
        },
    ]

    business_impact_results = [
        {
            "impact_id": "impact_exec_20260618_price_002",
            "action_id": "exec_20260618_price_002",
            "product_id": "ITEM-002",
            "product_uid": "product_shopee_br_ITEM-002",
            "platform": "Shopee",
            "action_type": "price",
            "action_status": "approved",
            "expected_impact": 3000.0,
            "actual_impact": 2840.0,
            "expected_profit_change": 2600.0,
            "profit_before": 620.0,
            "profit_after": 2940.0,
            "profit_delta": 2320.0,
            "stock_before": 122,
            "stock_after": 96,
            "stock_turnover_change": -3.5,
            "gmv_before": 3600.0,
            "gmv_after": 12000.0,
            "gmv_delta": 8400.0,
            "attribution_note": "价格复核通过后，Shopee 缓存订单与利润结果显示利润改善，仍只做本地归因。",
            "measured_at": "2026-06-18T18:40:00-03:00",
            "source": "action_queue",
            "created_at": "2026-06-18T20:00:00-03:00",
        },
        {
            "impact_id": "impact_act_20260617_003",
            "action_id": "act_20260617_003",
            "product_id": "MLB-002",
            "product_uid": "prod_7bb2f310",
            "platform": "Mercado Livre",
            "action_type": "price_review",
            "action_status": "approved_local",
            "expected_impact": 1900.0,
            "actual_impact": 1680.0,
            "expected_profit_change": 1750.0,
            "profit_before": 1180.0,
            "profit_after": 2810.0,
            "profit_delta": 1630.0,
            "stock_before": 84,
            "stock_after": 66,
            "stock_turnover_change": -2.1,
            "gmv_before": 5200.0,
            "gmv_after": 11100.0,
            "gmv_delta": 5900.0,
            "attribution_note": "本地审批后的价格带复核带来更稳定利润，但仍需要继续观察竞争变化。",
            "measured_at": "2026-06-18T17:20:00-03:00",
            "source": "manual",
            "created_at": "2026-06-18T20:00:00-03:00",
        },
        {
            "impact_id": "impact_decision_20260615_sku001",
            "action_id": "decision_20260615_sku001",
            "product_id": "ITEM-001",
            "product_uid": "product_shopee_br_ITEM-001",
            "platform": "Shopee",
            "action_type": "decision_recommend",
            "action_status": "evaluated",
            "expected_impact": 4100.0,
            "actual_impact": 4480.0,
            "expected_profit_change": 3840.0,
            "profit_before": 0.0,
            "profit_after": 3840.0,
            "profit_delta": 3840.0,
            "stock_before": 240,
            "stock_after": 112,
            "stock_turnover_change": -5.8,
            "gmv_before": 0.0,
            "gmv_after": 5107.2,
            "gmv_delta": 5107.2,
            "attribution_note": "决策反馈记录显示 RECOMMEND 后销售与 ROI 表现为正，用于评估决策有效性。",
            "measured_at": "2026-06-17T18:00:00-03:00",
            "source": "decision_feedback",
            "created_at": "2026-06-18T20:00:00-03:00",
        },
        {
            "impact_id": "impact_exec_20260618_ad_003",
            "action_id": "exec_20260618_ad_003",
            "product_id": "AMZ-005",
            "product_uid": "product_amazon_br_AMZ-005",
            "platform": "Amazon BR",
            "action_type": "ad",
            "action_status": "rejected",
            "expected_impact": 1800.0,
            "actual_impact": 420.0,
            "expected_profit_change": 1500.0,
            "profit_before": 2140.0,
            "profit_after": 2140.0,
            "profit_delta": 0.0,
            "stock_before": 76,
            "stock_after": 76,
            "stock_turnover_change": 0.0,
            "gmv_before": 7400.0,
            "gmv_after": 7400.0,
            "gmv_delta": 0.0,
            "attribution_note": "广告动作被财务拒绝，没有发生平台写操作；实际影响仅记录为风险控制收益。",
            "measured_at": "2026-06-18T18:55:00-03:00",
            "source": "action_queue",
            "created_at": "2026-06-18T20:00:00-03:00",
        },
        {
            "impact_id": "impact_act_20260617_004",
            "action_id": "act_20260617_004",
            "product_id": "AMZ-003",
            "product_uid": "prod_2c0d88aa",
            "platform": "Amazon BR",
            "action_type": "image_review",
            "action_status": "rejected_local",
            "expected_impact": 1200.0,
            "actual_impact": -180.0,
            "expected_profit_change": 900.0,
            "profit_before": 480.0,
            "profit_after": 300.0,
            "profit_delta": -180.0,
            "stock_before": 44,
            "stock_after": 42,
            "stock_turnover_change": 1.4,
            "gmv_before": 2100.0,
            "gmv_after": 1980.0,
            "gmv_delta": -120.0,
            "attribution_note": "主图方向被拒绝后未推进，后续表现偏弱，归入需复盘策略。",
            "measured_at": "2026-06-18T16:30:00-03:00",
            "source": "manual",
            "created_at": "2026-06-18T20:00:00-03:00",
        },
    ]

    profit_snapshot = [
        {
            "profit_snapshot_id": "profit_snapshot_20260617_br",
            "reporting_date": "2026-06-17",
            "market_code": "br",
            "yesterday_net_profit": 18640.0,
            "month_net_profit": 324800.0,
            "net_margin": 0.187,
            "cash_flow": 13220.0,
            "inventory_turnover_days": 41.0,
            "procurement_cost": 118400.0,
            "advertising_cost": 46200.0,
            "logistics_cost": 28700.0,
            "platform_commission": 21400.0,
            "tax_cost": 16800.0,
            "created_at": "2026-06-17T11:00:00-03:00",
        }
    ]

    product_profit = [
        {
            "profit_item_id": "profit_item_20260617_001",
            "reporting_date": "2026-06-17",
            "platform": "Shopee",
            "market_code": "br",
            "product_uid": "prod_8fd1a2c0",
            "product_name": "Organizador de Cozinha Modular",
            "revenue": 68400.0,
            "procurement_cost": 27800.0,
            "advertising_cost": 9100.0,
            "logistics_cost": 6200.0,
            "platform_commission": 3800.0,
            "tax_cost": 1700.0,
            "cost": 48600.0,
            "gross_profit": 19800.0,
            "net_profit": 14100.0,
            "net_margin": 0.206,
            "inventory_days": 28.0,
            "risk_level": "low",
            "created_at": "2026-06-17T11:05:00-03:00",
        },
        {
            "profit_item_id": "profit_item_20260617_002",
            "reporting_date": "2026-06-17",
            "platform": "TikTok Shop BR",
            "market_code": "br",
            "product_uid": "prod_97c41f03",
            "product_name": "Kit Skincare Viagem",
            "revenue": 91200.0,
            "procurement_cost": 39600.0,
            "advertising_cost": 16400.0,
            "logistics_cost": 7600.0,
            "platform_commission": 4900.0,
            "tax_cost": 1700.0,
            "cost": 70200.0,
            "gross_profit": 21000.0,
            "net_profit": 9800.0,
            "net_margin": 0.107,
            "inventory_days": 14.0,
            "risk_level": "high",
            "created_at": "2026-06-17T11:06:00-03:00",
        },
        {
            "profit_item_id": "profit_item_20260617_003",
            "reporting_date": "2026-06-17",
            "platform": "Mercado Livre",
            "market_code": "br",
            "product_uid": "prod_7bb2f310",
            "product_name": "Garrafa Termica Inox 750ml",
            "revenue": 55600.0,
            "procurement_cost": 23400.0,
            "advertising_cost": 8400.0,
            "logistics_cost": 5600.0,
            "platform_commission": 3100.0,
            "tax_cost": 1600.0,
            "cost": 42100.0,
            "gross_profit": 13500.0,
            "net_profit": 9200.0,
            "net_margin": 0.165,
            "inventory_days": 35.0,
            "risk_level": "medium",
            "created_at": "2026-06-17T11:07:00-03:00",
        },
        {
            "profit_item_id": "profit_item_20260617_004",
            "reporting_date": "2026-06-17",
            "platform": "Temu",
            "market_code": "br",
            "product_uid": "prod_5d4e1c7b",
            "product_name": "Suporte Magnetico para Celular no Carro",
            "revenue": 47200.0,
            "procurement_cost": 20200.0,
            "advertising_cost": 6100.0,
            "logistics_cost": 4300.0,
            "platform_commission": 2600.0,
            "tax_cost": 1400.0,
            "cost": 34600.0,
            "gross_profit": 12600.0,
            "net_profit": 7600.0,
            "net_margin": 0.161,
            "inventory_days": 31.0,
            "risk_level": "medium",
            "created_at": "2026-06-17T11:08:00-03:00",
        },
        {
            "profit_item_id": "profit_item_20260617_005",
            "reporting_date": "2026-06-17",
            "platform": "Amazon BR",
            "market_code": "br",
            "product_uid": "prod_2c0d88aa",
            "product_name": "Luminaria LED Recarregavel",
            "revenue": 38200.0,
            "procurement_cost": 20100.0,
            "advertising_cost": 5700.0,
            "logistics_cost": 4100.0,
            "platform_commission": 2200.0,
            "tax_cost": 1200.0,
            "cost": 33300.0,
            "gross_profit": 4900.0,
            "net_profit": 2500.0,
            "net_margin": 0.065,
            "inventory_days": 49.0,
            "risk_level": "high",
            "created_at": "2026-06-17T11:09:00-03:00",
        },
        {
            "profit_item_id": "profit_item_20260617_006",
            "reporting_date": "2026-06-17",
            "platform": "AliExpress",
            "market_code": "br",
            "product_uid": "prod_f42ab991",
            "product_name": "Mini Seladora Portatil para Embalagem",
            "revenue": 26400.0,
            "procurement_cost": 14600.0,
            "advertising_cost": 4300.0,
            "logistics_cost": 3700.0,
            "platform_commission": 2400.0,
            "tax_cost": 3100.0,
            "cost": 28100.0,
            "gross_profit": -1700.0,
            "net_profit": -2900.0,
            "net_margin": -0.11,
            "inventory_days": 58.0,
            "risk_level": "high",
            "created_at": "2026-06-17T11:10:00-03:00",
        },
    ]

    inventory_snapshot = [
        {
            "inventory_snapshot_id": "inventory_snapshot_20260617_br",
            "reporting_date": "2026-06-17",
            "market_code": "br",
            "total_inventory_value": 186900.0,
            "inventory_turnover_days": 39.5,
            "stock_health_score": 74.0,
            "stockout_risk_count": 2,
            "overstock_risk_count": 1,
            "slow_moving_sku_count": 1,
            "created_at": "2026-06-17T11:20:00-03:00",
        }
    ]

    inventory_stock = [
        {
            "inventory_item_id": "inventory_item_20260617_001",
            "reporting_date": "2026-06-17",
            "platform": "Shopee",
            "market_code": "br",
            "product_uid": "prod_8fd1a2c0",
            "product_name": "Organizador de Cozinha Modular",
            "stock_qty": 164,
            "daily_sales_avg": 7.8,
            "days_of_stock": 21.0,
            "reorder_point": 78,
            "suggested_reorder_qty": 48,
            "stock_status": "healthy",
            "inventory_value": 65200.0,
            "created_at": "2026-06-17T11:21:00-03:00",
        },
        {
            "inventory_item_id": "inventory_item_20260617_002",
            "reporting_date": "2026-06-17",
            "platform": "TikTok Shop BR",
            "market_code": "br",
            "product_uid": "prod_97c41f03",
            "product_name": "Kit Skincare Viagem",
            "stock_qty": 42,
            "daily_sales_avg": 6.1,
            "days_of_stock": 6.9,
            "reorder_point": 85,
            "suggested_reorder_qty": 180,
            "stock_status": "stockout_risk",
            "inventory_value": 20400.0,
            "created_at": "2026-06-17T11:22:00-03:00",
        },
        {
            "inventory_item_id": "inventory_item_20260617_003",
            "reporting_date": "2026-06-17",
            "platform": "Mercado Livre",
            "market_code": "br",
            "product_uid": "prod_7bb2f310",
            "product_name": "Garrafa Termica Inox 750ml",
            "stock_qty": 118,
            "daily_sales_avg": 3.4,
            "days_of_stock": 34.7,
            "reorder_point": 51,
            "suggested_reorder_qty": 0,
            "stock_status": "healthy",
            "inventory_value": 39800.0,
            "created_at": "2026-06-17T11:23:00-03:00",
        },
        {
            "inventory_item_id": "inventory_item_20260617_004",
            "reporting_date": "2026-06-17",
            "platform": "Temu",
            "market_code": "br",
            "product_uid": "prod_5d4e1c7b",
            "product_name": "Suporte Magnetico para Celular no Carro",
            "stock_qty": 410,
            "daily_sales_avg": 2.3,
            "days_of_stock": 178.3,
            "reorder_point": 30,
            "suggested_reorder_qty": 0,
            "stock_status": "overstock_risk",
            "inventory_value": 28900.0,
            "created_at": "2026-06-17T11:24:00-03:00",
        },
        {
            "inventory_item_id": "inventory_item_20260617_005",
            "reporting_date": "2026-06-17",
            "platform": "Amazon BR",
            "market_code": "br",
            "product_uid": "prod_2c0d88aa",
            "product_name": "Luminaria LED Recarregavel",
            "stock_qty": 67,
            "daily_sales_avg": 1.4,
            "days_of_stock": 47.9,
            "reorder_point": 24,
            "suggested_reorder_qty": 0,
            "stock_status": "slow_moving",
            "inventory_value": 17100.0,
            "created_at": "2026-06-17T11:25:00-03:00",
        },
        {
            "inventory_item_id": "inventory_item_20260617_006",
            "reporting_date": "2026-06-17",
            "platform": "AliExpress",
            "market_code": "br",
            "product_uid": "prod_f42ab991",
            "product_name": "Mini Seladora Portatil para Embalagem",
            "stock_qty": 24,
            "daily_sales_avg": 2.8,
            "days_of_stock": 8.6,
            "reorder_point": 45,
            "suggested_reorder_qty": 126,
            "stock_status": "reorder_soon",
            "inventory_value": 15500.0,
            "created_at": "2026-06-17T11:26:00-03:00",
        },
    ]

    inventory_risk = [
        {
            "risk_id": "inventory_risk_20260617_001",
            "reporting_date": "2026-06-17",
            "platform": "TikTok Shop BR",
            "market_code": "br",
            "product_uid": "prod_97c41f03",
            "risk_type": "stockout_risk",
            "risk_level": "high",
            "risk_reason": "At current run rate the stock cover is under 7 days.",
            "suggested_action": "Review replenishment timing manually before demand acceleration increases stockout pressure.",
            "created_at": "2026-06-17T11:27:00-03:00",
        },
        {
            "risk_id": "inventory_risk_20260617_002",
            "reporting_date": "2026-06-17",
            "platform": "AliExpress",
            "market_code": "br",
            "product_uid": "prod_f42ab991",
            "risk_type": "stockout_risk",
            "risk_level": "medium",
            "risk_reason": "The stock cover is below the normal inbound lead-time window.",
            "suggested_action": "Confirm supplier lead time and stage a low-risk reorder review if inbound supply is stable.",
            "created_at": "2026-06-17T11:28:00-03:00",
        },
        {
            "risk_id": "inventory_risk_20260617_003",
            "reporting_date": "2026-06-17",
            "platform": "Temu",
            "market_code": "br",
            "product_uid": "prod_5d4e1c7b",
            "risk_type": "overstock_risk",
            "risk_level": "high",
            "risk_reason": "Stock cover exceeds 170 days and is tying up working capital.",
            "suggested_action": "Review clearance pacing, demand assumptions, and whether the SKU should stay in the active assortment.",
            "created_at": "2026-06-17T11:29:00-03:00",
        },
        {
            "risk_id": "inventory_risk_20260617_004",
            "reporting_date": "2026-06-17",
            "platform": "Amazon BR",
            "market_code": "br",
            "product_uid": "prod_2c0d88aa",
            "risk_type": "slow_moving",
            "risk_level": "medium",
            "risk_reason": "Sales velocity is low while profit room is already thin.",
            "suggested_action": "Review price band and content quality manually before keeping the current stock depth.",
            "created_at": "2026-06-17T11:30:00-03:00",
        },
    ]

    reorder_recommendation = [
        {
            "recommendation_id": "reorder_20260617_001",
            "reporting_date": "2026-06-17",
            "platform": "TikTok Shop BR",
            "market_code": "br",
            "product_uid": "prod_97c41f03",
            "product_name": "Kit Skincare Viagem",
            "current_stock": 42,
            "daily_sales_avg": 6.1,
            "lead_time_days": 12,
            "recommended_reorder_qty": 180,
            "reorder_priority": "P1",
            "decision_notes": "Demand is still hot, so manual restock review should happen first.",
            "created_at": "2026-06-17T11:31:00-03:00",
        },
        {
            "recommendation_id": "reorder_20260617_002",
            "reporting_date": "2026-06-17",
            "platform": "AliExpress",
            "market_code": "br",
            "product_uid": "prod_f42ab991",
            "product_name": "Mini Seladora Portatil para Embalagem",
            "current_stock": 24,
            "daily_sales_avg": 2.8,
            "lead_time_days": 15,
            "recommended_reorder_qty": 126,
            "reorder_priority": "P1",
            "decision_notes": "Restock only after the supplier lead time is manually revalidated.",
            "created_at": "2026-06-17T11:32:00-03:00",
        },
        {
            "recommendation_id": "reorder_20260617_003",
            "reporting_date": "2026-06-17",
            "platform": "Shopee",
            "market_code": "br",
            "product_uid": "prod_8fd1a2c0",
            "product_name": "Organizador de Cozinha Modular",
            "current_stock": 164,
            "daily_sales_avg": 7.8,
            "lead_time_days": 10,
            "recommended_reorder_qty": 48,
            "reorder_priority": "P3",
            "decision_notes": "Current inventory is still healthy, so keep it as a low-priority reorder watch item.",
            "created_at": "2026-06-17T11:33:00-03:00",
        },
    ]

    upload_queue = [
        {
            "upload_id": "upload_20260616_001",
            "created_at": "2026-06-16T09:35:00-03:00",
            "platform": "Shopee",
            "market_code": "br",
            "platform_product_id": "ITEM-001",
            "platform_shop_id": "SHOP-001",
            "upload_request_type": "content_review",
            "target_id": "prod_8fd1a2c0",
            "payload_json": json.dumps({"requested_change": "title_update"}),
            "need_approval": 1,
            "approval_status": "pending_review",
            "status": "pending_review",
            "approved_by": None,
            "approved_at": None,
            "uploaded_at": None,
            "platform_response_json": None,
            "error_log": None,
            "notes": "Mock queue only. No platform write.",
        },
        {
            "upload_id": "upload_20260616_002",
            "created_at": "2026-06-16T09:55:00-03:00",
            "platform": "TikTok Shop BR",
            "market_code": "br",
            "platform_product_id": "TT-004",
            "platform_shop_id": "CREATOR-004",
            "upload_request_type": "listing_review",
            "target_id": "prod_97c41f03",
            "payload_json": json.dumps({"requested_change": "manual_compliance_check"}),
            "need_approval": 1,
            "approval_status": "pending_review",
            "status": "pending_review",
            "approved_by": None,
            "approved_at": None,
            "uploaded_at": None,
            "platform_response_json": None,
            "error_log": None,
            "notes": "Mock queue only. No platform write.",
        },
    ]

    crawl_logs = [
        {
            "crawl_run_id": "run_20260616_030000_001",
            "crawl_task_id": "task_br_market_scan_001",
            "platform": "Shopee",
            "market_code": "br",
            "started_at": "2026-06-16T03:00:00-03:00",
            "ended_at": "2026-06-16T03:04:22-03:00",
            "status": "success",
            "items_requested": 240,
            "items_captured": 236,
            "items_failed": 4,
            "error_type": None,
            "error_message": None,
            "retry_count": 0,
            "raw_output_path": "data/raw/run_20260616_030000_001.json",
            "notes": "Mock sync completed.",
        },
        {
            "crawl_run_id": "run_20260616_031000_002",
            "crawl_task_id": "task_br_market_scan_002",
            "platform": "Mercado Livre",
            "market_code": "br",
            "started_at": "2026-06-16T03:10:00-03:00",
            "ended_at": "2026-06-16T03:18:44-03:00",
            "status": "partial_success",
            "items_requested": 180,
            "items_captured": 172,
            "items_failed": 8,
            "error_type": "parse_warning",
            "error_message": "Some records were held for manual quality review.",
            "retry_count": 1,
            "raw_output_path": "data/raw/run_20260616_031000_002.json",
            "notes": "Mock sync completed with warnings.",
        },
        {
            "crawl_run_id": "run_20260616_032000_003",
            "crawl_task_id": "task_br_market_scan_003",
            "platform": "Amazon BR",
            "market_code": "br",
            "started_at": "2026-06-16T03:20:00-03:00",
            "ended_at": "2026-06-16T03:28:12-03:00",
            "status": "success",
            "items_requested": 130,
            "items_captured": 128,
            "items_failed": 2,
            "error_type": None,
            "error_message": None,
            "retry_count": 0,
            "raw_output_path": "data/raw/run_20260616_032000_003.json",
            "notes": "Mock sync completed.",
        },
    ]

    data_quality_report = [
        {
            "report_id": "dq_20260616_001",
            "report_date": "2026-06-16",
            "platform": "Shopee",
            "market_code": "br",
            "source_table": "raw_products",
            "check_name": "platform_product_id_present",
            "severity": "high",
            "status": "warning",
            "metric_value": 2.0,
            "threshold": 0.0,
            "details": "Two rows require manual field-completeness review.",
            "quality_status": "warning",
            "generated_at": "2026-06-16T10:40:00-03:00",
        },
        {
            "report_id": "dq_20260616_002",
            "report_date": "2026-06-16",
            "platform": "Mercado Livre",
            "market_code": "br",
            "source_table": "products",
            "check_name": "price_amount_valid",
            "severity": "medium",
            "status": "pass",
            "metric_value": 0.0,
            "threshold": 0.0,
            "details": "All seeded prices are numeric amounts.",
            "quality_status": "pass",
            "generated_at": "2026-06-16T10:40:00-03:00",
        },
        {
            "report_id": "dq_20260616_003",
            "report_date": "2026-06-16",
            "platform": "TikTok Shop BR",
            "market_code": "br",
            "source_table": "action_queue",
            "check_name": "human_approval_required",
            "severity": "high",
            "status": "pass",
            "metric_value": 3.0,
            "threshold": 3.0,
            "details": "All seeded actions remain in pending_review.",
            "quality_status": "pass",
            "generated_at": "2026-06-16T10:40:00-03:00",
        },
    ]

    return {
        "tenants": tenants,
        "workspaces": workspaces,
        "sellers": sellers,
        "products": products,
        "keywords": keywords,
        "market_score": market_score,
        "opportunity_score": opportunity_score,
        "analysis_queue": analysis_queue,
        "action_queue": action_queue,
        "action_history": action_history,
        "upload_queue": upload_queue,
        "approval_history": approval_history,
        "users": users,
        "roles": roles,
        "permissions": permissions,
        "user_roles": user_roles,
        "tenant_users": tenant_users,
        "operation_logs": operation_logs,
        "shopee_orders": shopee_orders,
        "shopee_products": shopee_products,
        "shopee_inventory": shopee_inventory,
        "decision_feedback": decision_feedback,
        "decision_history": decision_history,
        "decision_business_outcomes": decision_business_outcomes,
        "decision_learning_adjustments": decision_learning_adjustments,
        "business_impact_results": business_impact_results,
        "profit_snapshot": profit_snapshot,
        "product_profit": product_profit,
        "inventory_snapshot": inventory_snapshot,
        "inventory_stock": inventory_stock,
        "inventory_risk": inventory_risk,
        "reorder_recommendation": reorder_recommendation,
        "crawl_logs": crawl_logs,
        "data_quality_report": data_quality_report,
    }


def clear_tables(conn: sqlite3.Connection) -> None:
    for table_name in reversed(TABLE_ORDER):
        conn.execute(f"DELETE FROM {table_name}")


def insert_rows(conn: sqlite3.Connection, table_name: str, rows: list[dict[str, object]]) -> None:
    if not rows:
        return

    columns = list(rows[0].keys())
    for row in rows[1:]:
        for column in row.keys():
            if column not in columns:
                columns.append(column)

    placeholders = ", ".join("?" for _ in columns)
    column_clause = ", ".join(columns)
    values = [tuple(row.get(column) for column in columns) for row in rows]

    conn.executemany(
        f"INSERT INTO {table_name} ({column_clause}) VALUES ({placeholders})",
        values,
    )


def seed_database(db_path: Path) -> Path:
    db_path = init_database(db_path)
    rows = rows_to_insert()

    with sqlite3.connect(db_path) as conn:
        conn.execute("PRAGMA foreign_keys = ON;")
        clear_tables(conn)
        for table_name in TABLE_ORDER:
            insert_rows(conn, table_name, rows[table_name])
        conn.commit()

    return db_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Seed Brazil AI Commerce OS mock data into SQLite.")
    parser.add_argument(
        "--db-path",
        type=Path,
        default=DEFAULT_DB_PATH,
        help="Target SQLite database path.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    db_path = seed_database(args.db_path.resolve())
    print(f"Seeded SQLite database at: {db_path}")
    print("Inserted rows:")
    for table_name, rows in rows_to_insert().items():
        print(f"- {table_name}: {len(rows)}")


if __name__ == "__main__":
    main()
